
import React, { useState } from 'react';
import { Layout } from "@/components/layout/Layout";
import DashboardSidebar from "@/components/dashboard/DashboardSidebar";
import { useLanguage } from '@/contexts/LanguageContext';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';
import { Calendar as CalendarIcon, Download, FileText, Mail, Printer, Share2 } from 'lucide-react';
import { Calendar } from "@/components/ui/calendar";
import { Popover, PopoverTrigger, PopoverContent } from "@/components/ui/popover";
import { format } from 'date-fns';

const DashboardReports = () => {
  const { language } = useLanguage();
  const [date, setDate] = useState<Date | undefined>(new Date());
  
  const translations = {
    en: {
      title: "Reports",
      generate: "Generate Report",
      export: "Export",
      share: "Share",
      print: "Print",
      download: "Download",
      email: "Email",
      dateRange: "Date Range",
      reportType: "Report Type",
      reportTypes: {
        monthly: "Monthly Summary",
        quarterly: "Quarterly Analysis",
        annual: "Annual Report",
        custom: "Custom Report"
      },
      categories: {
        recycling: "Recycling Summary",
        impact: "Environmental Impact",
        rewards: "Rewards & Points",
        certificates: "Certificates"
      },
      metrics: {
        total: "Total E-waste (kg)",
        carbon: "Carbon Savings (kg)",
        trees: "Trees Saved",
        points: "Green Points Earned",
        pickups: "Total Pickups"
      },
      tables: {
        date: "Date",
        type: "Type",
        weight: "Weight",
        points: "Points",
        status: "Status"
      },
      selectDate: "Select date",
      autogenerated: "This is an auto-generated report based on your recycling activity",
      recyclingHistory: "Recycling History",
      environmentalImpact: "Environmental Impact",
      rewards: "Rewards & Points",
      periodSummary: "Period Summary"
    },
    es: {
      title: "Informes",
      generate: "Generar Informe",
      export: "Exportar",
      share: "Compartir",
      print: "Imprimir",
      download: "Descargar",
      email: "Correo",
      dateRange: "Rango de Fechas",
      reportType: "Tipo de Informe",
      reportTypes: {
        monthly: "Resumen Mensual",
        quarterly: "Análisis Trimestral",
        annual: "Informe Anual",
        custom: "Informe Personalizado"
      },
      categories: {
        recycling: "Resumen de Reciclaje",
        impact: "Impacto Ambiental",
        rewards: "Recompensas y Puntos",
        certificates: "Certificados"
      },
      metrics: {
        total: "Total Residuos Electrónicos (kg)",
        carbon: "Ahorro de Carbono (kg)",
        trees: "Árboles Salvados",
        points: "Puntos Verdes Ganados",
        pickups: "Total de Recogidas"
      },
      tables: {
        date: "Fecha",
        type: "Tipo",
        weight: "Peso",
        points: "Puntos",
        status: "Estado"
      },
      selectDate: "Seleccionar fecha",
      autogenerated: "Este es un informe generado automáticamente basado en su actividad de reciclaje",
      recyclingHistory: "Historial de Reciclaje",
      environmentalImpact: "Impacto Ambiental",
      rewards: "Recompensas y Puntos",
      periodSummary: "Resumen del Período"
    }
  };
  
  // Default to English if the language is not supported
  const t = translations[language.code as keyof typeof translations] || translations.en;

  // Sample data
  const monthlyData = [
    { name: 'Jan', ewaste: 30, points: 150 },
    { name: 'Feb', ewaste: 45, points: 225 },
    { name: 'Mar', ewaste: 40, points: 200 },
    { name: 'Apr', ewaste: 55, points: 275 },
    { name: 'May', ewaste: 65, points: 325 },
    { name: 'Jun', ewaste: 75, points: 375 }
  ];

  const impactData = [
    { name: 'Carbon Saved', value: 240 },
    { name: 'Water Saved', value: 120 },
    { name: 'Energy Saved', value: 180 },
    { name: 'Materials Recovered', value: 200 }
  ];

  const COLORS = ['#10B981', '#3B82F6', '#F59E0B', '#EC4899'];

  const recyclingHistory = [
    { 
      id: 1, 
      date: '2023-06-15', 
      type: 'Electronics', 
      weight: '5.2 kg', 
      points: 52, 
      status: 'Completed' 
    },
    { 
      id: 2, 
      date: '2023-06-28', 
      type: 'Batteries', 
      weight: '1.7 kg', 
      points: 34, 
      status: 'Completed' 
    },
    { 
      id: 3, 
      date: '2023-07-12', 
      type: 'Appliances', 
      weight: '12.4 kg', 
      points: 124, 
      status: 'Completed' 
    },
    { 
      id: 4, 
      date: '2023-07-25', 
      type: 'Cables & Wires', 
      weight: '2.3 kg', 
      points: 46, 
      status: 'Completed' 
    },
  ];

  return (
    <Layout>
      <div className="flex">
        <DashboardSidebar />
        <main className="flex-1 p-6 bg-background">
          <div className="flex justify-between items-center mb-6">
            <h1 className="text-2xl font-bold">{t.title}</h1>
            <div className="flex gap-2">
              <Button className="bg-eco-green hover:bg-eco-green-dark">
                {t.generate}
              </Button>
            </div>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-[300px_1fr] gap-6 mb-6">
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">{t.reportType}</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <label className="text-sm font-medium">{t.reportType}</label>
                  <Select defaultValue="monthly">
                    <SelectTrigger>
                      <SelectValue placeholder={t.reportTypes.monthly} />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="monthly">{t.reportTypes.monthly}</SelectItem>
                      <SelectItem value="quarterly">{t.reportTypes.quarterly}</SelectItem>
                      <SelectItem value="annual">{t.reportTypes.annual}</SelectItem>
                      <SelectItem value="custom">{t.reportTypes.custom}</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                
                <div className="space-y-2">
                  <label className="text-sm font-medium">{t.dateRange}</label>
                  <div className="grid gap-2">
                    <Popover>
                      <PopoverTrigger asChild>
                        <Button
                          variant={"outline"}
                          className="w-full justify-start text-left font-normal"
                        >
                          <CalendarIcon className="mr-2 h-4 w-4" />
                          {date ? format(date, "PPP") : t.selectDate}
                        </Button>
                      </PopoverTrigger>
                      <PopoverContent className="w-auto p-0">
                        <Calendar
                          mode="single"
                          selected={date}
                          onSelect={setDate}
                          initialFocus
                        />
                      </PopoverContent>
                    </Popover>
                  </div>
                </div>
                
                <div className="space-y-2">
                  <label className="text-sm font-medium">Categories</label>
                  <div className="space-y-2">
                    {Object.entries(t.categories).map(([key, value]) => (
                      <div key={key} className="flex items-center">
                        <input type="checkbox" id={key} className="mr-2" defaultChecked />
                        <label htmlFor={key} className="text-sm">{value}</label>
                      </div>
                    ))}
                  </div>
                </div>
                
                <Button className="w-full bg-eco-green hover:bg-eco-green-dark">
                  {t.generate}
                </Button>
              </CardContent>
            </Card>
            
            <div className="space-y-6">
              <Card>
                <CardHeader className="flex flex-row items-center justify-between pb-2">
                  <div>
                    <CardTitle className="text-xl">June 2023 - {t.reportTypes.monthly}</CardTitle>
                    <CardDescription>{t.autogenerated}</CardDescription>
                  </div>
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm">
                      <Printer className="h-4 w-4 mr-1" /> {t.print}
                    </Button>
                    <Button variant="outline" size="sm">
                      <Download className="h-4 w-4 mr-1" /> {t.download}
                    </Button>
                    <Button variant="outline" size="sm">
                      <Mail className="h-4 w-4 mr-1" /> {t.email}
                    </Button>
                    <Button variant="outline" size="sm">
                      <Share2 className="h-4 w-4 mr-1" /> {t.share}
                    </Button>
                  </div>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-1 md:grid-cols-5 gap-4 mb-6">
                    <div className="bg-eco-soft rounded-lg p-4 text-center">
                      <p className="text-sm text-muted-foreground">{t.metrics.total}</p>
                      <p className="text-2xl font-bold text-eco-green">37.2</p>
                    </div>
                    <div className="bg-eco-soft rounded-lg p-4 text-center">
                      <p className="text-sm text-muted-foreground">{t.metrics.carbon}</p>
                      <p className="text-2xl font-bold text-eco-blue">23.4</p>
                    </div>
                    <div className="bg-eco-soft rounded-lg p-4 text-center">
                      <p className="text-sm text-muted-foreground">{t.metrics.trees}</p>
                      <p className="text-2xl font-bold text-amber-600">12</p>
                    </div>
                    <div className="bg-eco-soft rounded-lg p-4 text-center">
                      <p className="text-sm text-muted-foreground">{t.metrics.points}</p>
                      <p className="text-2xl font-bold text-eco-green">372</p>
                    </div>
                    <div className="bg-eco-soft rounded-lg p-4 text-center">
                      <p className="text-sm text-muted-foreground">{t.metrics.pickups}</p>
                      <p className="text-2xl font-bold text-eco-blue">4</p>
                    </div>
                  </div>
                  
                  <Tabs defaultValue="recycling" className="mt-6">
                    <TabsList className="mb-4">
                      <TabsTrigger value="recycling">{t.recyclingHistory}</TabsTrigger>
                      <TabsTrigger value="impact">{t.environmentalImpact}</TabsTrigger>
                      <TabsTrigger value="rewards">{t.rewards}</TabsTrigger>
                    </TabsList>
                    
                    <TabsContent value="recycling">
                      <div className="space-y-6">
                        <div className="h-[300px]">
                          <ResponsiveContainer width="100%" height="100%">
                            <BarChart data={monthlyData}>
                              <CartesianGrid strokeDasharray="3 3" />
                              <XAxis dataKey="name" />
                              <YAxis />
                              <Tooltip />
                              <Legend />
                              <Bar dataKey="ewaste" name="E-waste (kg)" fill="#10B981" />
                            </BarChart>
                          </ResponsiveContainer>
                        </div>
                        
                        <div>
                          <h3 className="text-lg font-medium mb-3">{t.recyclingHistory}</h3>
                          <div className="overflow-x-auto">
                            <table className="w-full border-collapse">
                              <thead>
                                <tr className="border-b">
                                  <th className="py-2 px-4 text-left font-semibold">{t.tables.date}</th>
                                  <th className="py-2 px-4 text-left font-semibold">{t.tables.type}</th>
                                  <th className="py-2 px-4 text-left font-semibold">{t.tables.weight}</th>
                                  <th className="py-2 px-4 text-left font-semibold">{t.tables.points}</th>
                                  <th className="py-2 px-4 text-left font-semibold">{t.tables.status}</th>
                                </tr>
                              </thead>
                              <tbody>
                                {recyclingHistory.map((item) => (
                                  <tr key={item.id} className="border-b">
                                    <td className="py-3 px-4">{new Date(item.date).toLocaleDateString()}</td>
                                    <td className="py-3 px-4">{item.type}</td>
                                    <td className="py-3 px-4">{item.weight}</td>
                                    <td className="py-3 px-4 font-medium">{item.points}</td>
                                    <td className="py-3 px-4">
                                      <span className="inline-block py-1 px-2 rounded-full bg-green-100 text-green-800 text-xs">
                                        {item.status}
                                      </span>
                                    </td>
                                  </tr>
                                ))}
                              </tbody>
                            </table>
                          </div>
                        </div>
                      </div>
                    </TabsContent>
                    
                    <TabsContent value="impact">
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div className="h-[300px]">
                          <ResponsiveContainer width="100%" height="100%">
                            <PieChart>
                              <Pie
                                data={impactData}
                                cx="50%"
                                cy="50%"
                                labelLine={false}
                                label={({ name, percent }) => `${name}: ${(percent * 100).toFixed(0)}%`}
                                outerRadius={100}
                                fill="#8884d8"
                                dataKey="value"
                              >
                                {impactData.map((entry, index) => (
                                  <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                                ))}
                              </Pie>
                              <Tooltip />
                            </PieChart>
                          </ResponsiveContainer>
                        </div>
                        
                        <div className="space-y-4">
                          <h3 className="text-lg font-medium">{t.environmentalImpact}</h3>
                          <div className="space-y-2">
                            <div className="bg-eco-soft rounded-md p-3">
                              <div className="flex justify-between">
                                <p>Carbon Emissions Saved</p>
                                <p className="font-bold">23.4 kg</p>
                              </div>
                              <p className="text-sm text-muted-foreground">Equivalent to 95.2 miles not driven by an average car</p>
                            </div>
                            <div className="bg-eco-soft rounded-md p-3">
                              <div className="flex justify-between">
                                <p>Water Saved</p>
                                <p className="font-bold">437 liters</p>
                              </div>
                              <p className="text-sm text-muted-foreground">Equivalent to 7.3 days of water usage for one person</p>
                            </div>
                            <div className="bg-eco-soft rounded-md p-3">
                              <div className="flex justify-between">
                                <p>Energy Saved</p>
                                <p className="font-bold">156 kWh</p>
                              </div>
                              <p className="text-sm text-muted-foreground">Equivalent to 5.2 days of household electricity use</p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </TabsContent>
                    
                    <TabsContent value="rewards">
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div className="h-[300px]">
                          <ResponsiveContainer width="100%" height="100%">
                            <LineChart data={monthlyData}>
                              <CartesianGrid strokeDasharray="3 3" />
                              <XAxis dataKey="name" />
                              <YAxis />
                              <Tooltip />
                              <Legend />
                              <Line type="monotone" dataKey="points" name="Green Points" stroke="#10B981" strokeWidth={2} />
                            </LineChart>
                          </ResponsiveContainer>
                        </div>
                        
                        <div className="space-y-4">
                          <h3 className="text-lg font-medium">{t.rewards}</h3>
                          <div className="bg-eco-soft rounded-md p-4">
                            <div className="flex justify-between items-center mb-2">
                              <p className="font-medium">Monthly Points Summary</p>
                              <p className="font-bold text-lg text-eco-green">372</p>
                            </div>
                            <div className="space-y-2 text-sm">
                              <div className="flex justify-between">
                                <p>Recycling Points</p>
                                <p>258</p>
                              </div>
                              <div className="flex justify-between">
                                <p>Educational Quiz Points</p>
                                <p>60</p>
                              </div>
                              <div className="flex justify-between">
                                <p>Referral Points</p>
                                <p>54</p>
                              </div>
                            </div>
                          </div>
                          <div className="bg-eco-soft rounded-md p-4">
                            <div className="flex justify-between items-center mb-2">
                              <p className="font-medium">Rewards Redeemed</p>
                              <p className="font-bold">1</p>
                            </div>
                            <div className="flex justify-between text-sm">
                              <p>10% Discount at EcoStore</p>
                              <p>300 points</p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </TabsContent>
                  </Tabs>
                </CardContent>
              </Card>
              
              <Card>
                <CardHeader>
                  <CardTitle className="text-lg">{t.periodSummary}</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    <p className="text-center text-lg">
                      During this period, you've recycled <span className="font-bold text-eco-green">37.2 kg</span> of e-waste
                      and earned <span className="font-bold text-eco-green">372 points</span>. Keep going!
                    </p>
                    
                    <div className="flex justify-center gap-4">
                      <Button variant="outline" className="bg-eco-soft border-0">
                        <FileText className="h-4 w-4 mr-2" />
                        Download Certificate
                      </Button>
                      <Button className="bg-eco-green hover:bg-eco-green-dark">
                        Schedule Next Pickup
                      </Button>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </main>
      </div>
    </Layout>
  );
};

export default DashboardReports;
