// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdpuoqdpcljynytbrmni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkcHVvcWRwY2xqeW55dGJybW5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MTMwNjksImV4cCI6MjA2MDE4OTA2OX0.XUn9h3-mgLniVA2efIlLM1O4-nqOuz5Uo8MYKbu6l20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);